[package]
name = "i3-ipc"
version = "0.1.0"
edition = "2024"

[dependencies]
i3ipc-jl = "0.11.2"
image = "0.25.6"
regex = "1.11.1"
x11rb = "0.13.1"
dbus = "0.9"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
